# Comprehensive Apple Health Measurement Configuration
# Supports all 56+ data types found in Apple Health exports

measurements:
  # ============================================================================
  # VITAL SIGNS & HEART HEALTH
  # ============================================================================
  vitals:
    description: "Heart rate and cardiovascular data"
    types:
      - "HKQuantityTypeIdentifierHeartRate"
      - "HKQuantityTypeIdentifierRestingHeartRate"
      - "HKQuantityTypeIdentifierHeartRateRecoveryOneMinute"
      - "HKQuantityTypeIdentifierHeartRateVariabilitySDNN"
      - "HKQuantityTypeIdentifierWalkingHeartRateAverage"
    measurement_name: "heart_metrics"
    fields:
      heart_rate: "value"
      resting_hr: "resting_value"
      recovery_hr: "recovery_value"
      hrv: "hrv_value"
      walking_avg_hr: "walking_avg_value"
    tags:
      - device
      - source
      - motion_context
      - metric_type
    validation:
      enabled: true
      rules:
        heart_rate:
          min: 30
          max: 250
          typical_min: 50
          typical_max: 200
        resting_hr:
          min: 30
          max: 120
          typical_min: 40
          typical_max: 100
        recovery_hr:
          min: 5    # Heart rate recovery can be very low for fit individuals
          max: 80
          typical_min: 10
          typical_max: 60
        hrv:
          min: 5    # HRV can be quite low, especially during stress/illness
          max: 300
          typical_min: 15
          typical_max: 100
        walking_avg_hr:
          min: 50
          max: 200
          typical_min: 70
          typical_max: 150

  # ============================================================================
  # RESPIRATORY & BLOOD METRICS
  # ============================================================================
  respiratory:
    description: "Breathing and blood oxygen measurements"
    types:
      - "HKQuantityTypeIdentifierOxygenSaturation"
      - "HKQuantityTypeIdentifierRespiratoryRate"
    measurement_name: "respiratory_metrics"
    fields:
      oxygen_saturation: "value"
      respiratory_rate: "value"
    tags:
      - device
      - source
      - measurement_context
    validation:
      enabled: true
      rules:
        oxygen_saturation:
          min: 70
          max: 100
          typical_min: 95
          typical_max: 100
        respiratory_rate:
          min: 8
          max: 40
          typical_min: 12
          typical_max: 20

  # ============================================================================
  # BODY COMPOSITION & PHYSICAL CHARACTERISTICS
  # ============================================================================
  body_metrics:
    description: "Body mass, height, and composition data"
    types:
      - "HKQuantityTypeIdentifierBodyMass"
      - "HKQuantityTypeIdentifierHeight"
    measurement_name: "body_composition"
    fields:
      weight: "value"
      height: "value"
    tags:
      - device
      - source
      - measurement_type
    validation:
      enabled: true
      rules:
        weight:
          min: 20
          max: 300
          typical_min: 40
          typical_max: 150
        height:
          min: 50
          max: 250
          typical_min: 140
          typical_max: 210

  # ============================================================================
  # ENERGY & ACTIVITY TRACKING
  # ============================================================================
  energy:
    description: "Calorie burn and energy expenditure"
    types:
      - "HKQuantityTypeIdentifierActiveEnergyBurned"
      - "HKQuantityTypeIdentifierBasalEnergyBurned"
      - "HKQuantityTypeIdentifierAppleExerciseTime"
      - "HKQuantityTypeIdentifierAppleStandTime"
      - "HKCategoryTypeIdentifierAppleStandHour"
    measurement_name: "energy_metrics"
    fields:
      active_energy: "value"
      basal_energy: "value"
      exercise_time: "value"
      stand_time: "value"
      stand_hours: "count"
    tags:
      - energy_type
      - activity_type
      - device
      - source
    validation:
      enabled: true
      rules:
        active_energy:
          min: 0
          max: 8000
          typical_min: 0
          typical_max: 4000
        basal_energy:
          min: 500
          max: 5000
          typical_min: 1200
          typical_max: 2500

  # ============================================================================
  # MOVEMENT & STEP TRACKING
  # ============================================================================
  movement:
    description: "Steps, distance, and movement patterns"
    types:
      - "HKQuantityTypeIdentifierStepCount"
      - "HKQuantityTypeIdentifierDistanceWalkingRunning"
      - "HKQuantityTypeIdentifierFlightsClimbed"
      - "HKQuantityTypeIdentifierPhysicalEffort"
    measurement_name: "movement_metrics"
    fields:
      steps: "count"
      distance: "value"
      flights_climbed: "count"
      physical_effort: "value"
    tags:
      - movement_type
      - device
      - source
    validation:
      enabled: true
      rules:
        steps:
          min: 0
          max: 100000
          typical_min: 0
          typical_max: 30000
        distance:
          min: 0
          max: 200000
          typical_min: 0
          typical_max: 50000

  # ============================================================================
  # RUNNING & ATHLETIC PERFORMANCE
  # ============================================================================
  running_metrics:
    description: "Advanced running and athletic performance data"
    types:
      - "HKQuantityTypeIdentifierRunningSpeed"
      - "HKQuantityTypeIdentifierRunningPower"
      - "HKQuantityTypeIdentifierRunningStrideLength"
      - "HKQuantityTypeIdentifierRunningGroundContactTime"
      - "HKQuantityTypeIdentifierRunningVerticalOscillation"
    measurement_name: "running_performance"
    fields:
      speed: "value"
      power: "value"
      stride_length: "value"
      ground_contact_time: "value"
      vertical_oscillation: "value"
    tags:
      - metric_type
      - device
      - source
      - workout_context
    validation:
      enabled: true
      rules:
        speed:
          min: 0
          max: 30
          typical_min: 2
          typical_max: 20
        power:
          min: 0
          max: 2000
          typical_min: 100
          typical_max: 800

  # ============================================================================
  # WALKING & GAIT ANALYSIS
  # ============================================================================
  walking_metrics:
    description: "Walking patterns and gait analysis"
    types:
      - "HKQuantityTypeIdentifierWalkingSpeed"
      - "HKQuantityTypeIdentifierWalkingStepLength"
      - "HKQuantityTypeIdentifierWalkingAsymmetryPercentage"
      - "HKQuantityTypeIdentifierWalkingDoubleSupportPercentage"
      - "HKQuantityTypeIdentifierAppleWalkingSteadiness"
      - "HKQuantityTypeIdentifierStairAscentSpeed"
      - "HKQuantityTypeIdentifierStairDescentSpeed"
    measurement_name: "walking_analysis"
    fields:
      walking_speed: "value"
      step_length: "value"
      asymmetry: "value"
      double_support: "value"
      steadiness: "value"
      stair_ascent_speed: "value"
      stair_descent_speed: "value"
    tags:
      - analysis_type
      - device
      - source
    validation:
      enabled: true
      rules:
        walking_speed:
          min: 0
          max: 10
          typical_min: 0.5
          typical_max: 6

  # ============================================================================
  # CYCLING & SPORT-SPECIFIC DISTANCES
  # ============================================================================
  cycling_sports:
    description: "Cycling and sport-specific distance tracking"
    types:
      - "HKQuantityTypeIdentifierDistanceCycling"
      - "HKQuantityTypeIdentifierDistanceSwimming"
      - "HKQuantityTypeIdentifierDistanceCrossCountrySkiing"
      - "HKQuantityTypeIdentifierDistanceDownhillSnowSports"
      - "HKQuantityTypeIdentifierDistanceSkatingSports"
      - "HKQuantityTypeIdentifierCrossCountrySkiingSpeed"
    measurement_name: "sports_distance"
    fields:
      cycling_distance: "value"
      swimming_distance: "value"
      skiing_distance: "value"
      downhill_distance: "value"
      skating_distance: "value"
      skiing_speed: "value"
    tags:
      - sport_type
      - device
      - source
      - workout_context
    validation:
      enabled: true
      rules:
        distance:
          min: 0
          max: 1000000
          typical_min: 0
          typical_max: 200000

  # ============================================================================
  # SWIMMING & WATER SPORTS
  # ============================================================================
  swimming_metrics:
    description: "Swimming and water activity metrics"
    types:
      - "HKQuantityTypeIdentifierSwimmingStrokeCount"
      - "HKQuantityTypeIdentifierUnderwaterDepth"
      - "HKQuantityTypeIdentifierWaterTemperature"
    measurement_name: "swimming_performance"
    fields:
      stroke_count: "count"
      depth: "value"
      water_temperature: "value"
    tags:
      - swimming_type
      - device
      - source
    validation:
      enabled: true
      rules:
        depth:
          min: 0
          max: 200
          typical_min: 0
          typical_max: 50
        water_temperature:
          min: -5
          max: 50
          typical_min: 10
          typical_max: 35

  # ============================================================================
  # FITNESS & CARDIO METRICS
  # ============================================================================
  fitness:
    description: "Overall fitness and cardio performance"
    types:
      - "HKQuantityTypeIdentifierVO2Max"
      - "HKQuantityTypeIdentifierSixMinuteWalkTestDistance"
    measurement_name: "fitness_metrics"
    fields:
      vo2_max: "value"
      six_minute_walk_distance: "value"
    tags:
      - fitness_test_type
      - device
      - source
    validation:
      enabled: true
      rules:
        vo2_max:
          min: 10
          max: 80
          typical_min: 20
          typical_max: 60

  # ============================================================================
  # SLEEP & RECOVERY
  # ============================================================================
  sleep:
    description: "Sleep analysis, temperature, and recovery metrics"
    types:
      - "HKCategoryTypeIdentifierSleepAnalysis"
      - "HKQuantityTypeIdentifierAppleSleepingWristTemperature"
      - "HKQuantityTypeIdentifierAppleSleepingBreathingDisturbances"
      - "HKDataTypeSleepDurationGoal"
    measurement_name: "sleep_metrics"
    fields:
      duration: "value"
      temperature: "value"
      breathing_disturbances: "count"
      sleep_goal: "goal_value"
    tags:
      - sleep_state
      - sleep_stage
      - device
      - source
    validation:
      enabled: true
      rules:
        duration:
          min: 30
          max: 50000
          typical_min: 240
          typical_max: 720
        temperature:
          min: 30
          max: 45
          typical_min: 35
          typical_max: 38

  # ============================================================================
  # ENVIRONMENTAL & AUDIO EXPOSURE
  # ============================================================================
  environmental:
    description: "Environmental factors and audio exposure"
    types:
      - "HKQuantityTypeIdentifierEnvironmentalAudioExposure"
      - "HKQuantityTypeIdentifierHeadphoneAudioExposure"
      - "HKCategoryTypeIdentifierAudioExposureEvent"
      - "HKQuantityTypeIdentifierTimeInDaylight"
    measurement_name: "environmental_metrics"
    fields:
      environmental_audio: "value"
      headphone_audio: "value"
      audio_events: "count"
      daylight_time: "value"
    tags:
      - exposure_type
      - device
      - source
      - event_type
    validation:
      enabled: true
      rules:
        audio_exposure:
          min: 0
          max: 120
          typical_min: 30
          typical_max: 85

  # ============================================================================
  # WORKOUTS & ACTIVITIES
  # ============================================================================
  workouts:
    description: "Workout sessions and activity summaries"
    types:
      - "HKWorkoutTypeIdentifier"
      - "HKActivitySummary"
      # Workout Events
      - "HKWorkoutEventTypeLap"
      - "HKWorkoutEventTypeMarker"
      - "HKWorkoutEventTypeMotionPaused"
      - "HKWorkoutEventTypeMotionResumed"
      - "HKWorkoutEventTypePause"
      - "HKWorkoutEventTypeResume"
      - "HKWorkoutEventTypeSegment"
    measurement_name: "workout_sessions"
    fields:
      duration: "duration"
      energy: "value"
      distance: "distance"
      move_time: "move_minutes"
      exercise_time: "exercise_minutes"
      stand_hours: "stand_hours"
      energy_goal: "target"
      laps: "lap_count"
      segments: "segment_count"
    tags:
      - activity_type
      - workout_type
      - summary_type
      - event_type
      - device
      - source
    validation:
      enabled: true
      rules:
        duration:
          min: 60
          max: 43200
          typical_min: 300
          typical_max: 7200
        energy:
          min: 0
          max: 8000
          typical_min: 50
          typical_max: 2000

# ============================================================================
# GLOBAL CONFIGURATION
# ============================================================================
global:
  batch_size: 1000
  duplicate_check_window_hours: 24
  default_timezone: "UTC"
  
  # Data quality settings
  validation:
    strict_mode: false  # If true, validation errors prevent import
    log_warnings: true
    
  # Performance settings
  performance:
    max_retries: 3
    retry_delay_base: 2  # seconds, exponential backoff base
    
  # Import behavior
  import:
    skip_unknown_types: false  # Log unknown types but continue
    create_measurements_on_demand: true  # Auto-create InfluxDB measurements