# Measurement Configuration for Apple Health Importer
# This file defines how Apple Health data types are mapped to InfluxDB measurements

measurements:
  vitals:
    description: "Heart rate and vital signs data"
    types:
      - "HKQuantityTypeIdentifierHeartRate"
    measurement_name: "heartrate_bpm"
    fields:
      heart_rate: "value"
    tags:
      - device
      - source
      - motion_context
    validation:
      enabled: true
      rules:
        value:
          min: 30
          max: 250
          typical_min: 40
          typical_max: 200
  
  activity:
    description: "Physical activity, workouts, and energy data"
    types:
      - "HKQuantityTypeIdentifierStepCount"
      - "HKQuantityTypeIdentifierActiveEnergyBurned"
      - "HKQuantityTypeIdentifierBasalEnergyBurned"
      - "HKWorkoutTypeIdentifier"
      - "HKActivitySummary"
    measurement_name: "energy_kcal"
    fields:
      steps: "count"
      energy: "value"
      energy_goal: "target"
      distance: "distance"
      duration: "duration"
      move_time: "move_minutes"
      exercise_time: "exercise_minutes"
      stand_hours: "stand_hours"
    tags:
      - activity_type
      - energy_type
      - summary_type
      - device
      - source
    validation:
      enabled: true
      rules:
        active_calories:
          min: 0
          max: 8000
          typical_min: 0
          typical_max: 4000
        resting_calories:
          min: 500
          max: 3500
          typical_min: 1200
          typical_max: 2500
        workout_duration:
          min: 60
          max: 43200
          typical_min: 300
          typical_max: 7200
        workout_distance:
          min: 0
          max: 200000
          typical_min: 100
          typical_max: 50000
  
  sleep:
    description: "Sleep analysis and duration data"
    types:
      - "HKCategoryTypeIdentifierSleepAnalysis"
    measurement_name: "sleep_duration_min"
    fields:
      duration: "value"
      quality: "quality"
    tags:
      - state
      - device
      - source
    validation:
      enabled: true
      rules:
        sleep_duration:
          min: 30
          max: 1440
          typical_min: 240
          typical_max: 720

# Global settings
global:
  batch_size: 1000
  duplicate_check_window_hours: 24
  default_timezone: "UTC"
  
  # Data quality settings
  validation:
    strict_mode: false  # If true, validation errors prevent import
    log_warnings: true
    
  # Performance settings
  performance:
    max_retries: 3
    retry_delay_base: 2  # seconds, exponential backoff base